name: "Publish release"
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get latest version
        id: get_version
        run: |
          LATEST_VERSION=$(git tag --sort=-creatordate | head -1)
          VERSION_NUM=$(echo $LATEST_VERSION | sed -e "s/^.*\///")
          echo "{LATEST_VERSION}={$LATEST_VERSION}" >> $GITHUB_OUTPUT
          echo "{VERSION_NUM}={$VERSION_NUM}" >> $GITHUB_OUTPUT

      - name: Update version.yaml
        run: |
          sed -e "s/VERSION: \[.*\]/VERSION: \[${{ steps.get_version.outputs.VERSION_NUM }}\]/" version.yaml > tmpfile && mv tmpfile version.yaml

      - name: Commit updates
        uses: EndBug/add-and-commit@v7
        with:
          branch: master
          message: "Bump version: ${{ steps.get_version.outputs.LATEST_VERSION }}"
          tag: '${{ steps.get_version.outputs.LATEST_VERSION }} --force'
          tag_push: '--force'
          add: "['version.yaml']"          
