name: "Publish release"
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get latest version
        id: get_version
        run: |
          LATEST_VERSION=${{ github.event.release.tag_name }}
          VERSION_NUM=$(echo $LATEST_VERSION | sed -e "s/^.*\///")
          echo "{LATEST_VERSION}={$LATEST_VERSION}" >> $GITHUB_OUTPUT
          echo "{VERSION_NUM}={$VERSION_NUM}" >> $GITHUB_OUTPUT

      - name: Update version.yaml
        id: update_version_file
        run: |
          VERSION_NUM=${{ steps.get_version.outputs.VERSION_NUM }}
          sed -e "s/VERSION: \[.*\]/VERSION: \[ $VERSION_NUM \]/" version.yaml > tmpfile && mv tmpfile version.yaml
          git add ./version.yaml
          git config --local user.email "shimomatsubae@takumi-robo.com"
          git config --local user.name "shimoe"
          git commit -m "バージョン情報更新 $VERSION_NUM"
          git tag ${{ github.event.release.tag_name }} --force
          git push --tags
